#! /bin/bash

docker events | while read event; do
	event_type=$(echo $event | awk '{print $3}')
	echo $event_type | grep '\(kill\|stop\|start\|die\)' > /dev/null
	[[ $? != "0" ]] && continue
	echo $event_type
	id=$(echo $event | awk '{print $4}')
  inspect=$(docker inspect --format '{{ .Config.Hostname }} {{ .NetworkSettings.Ports }}' $id)
	subdomain=$(echo $inspect | awk '{print $1}')
	port=$(echo $inspect | awk '{print $3}' | sed 's/[^0-9]//g')
	config_path=/etc/nginx/sites-enabled/$subdomain
	if [[ $event_type == "start" ]]; then
	(cat > $config_path) <<EOF
server {
  listen 80;
  server_name $subdomain.nno.ooo;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://localhost:$port;
  }
}
EOF
	else
		rm $config_path
	fi

	systemctl reload nginx
done
