#! /bin/bash

which snap
if [[ $? == "1" ]]; then
	 apt-get install snapd
	 snap install core
	 echo "Installed snap; to continue installation, log out and in again, and re-run"
	 exit
fi

snap refresh core
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot
snap set certbot trust-plugin-with-root=ok
snap install certbot-dns-cloudflare

apt-get -y update
apt-get install nginx

path=$(realpath ./subdomx)
ln -fs $path /usr/local/bin/subdomx

certbot_creds=./certbot-cloudflare.ini
if [[ -f $certbot_creds ]]; then
  certbot certonly --dns-cloudflare --dns-cloudflare-credentials $cerbot_creds
	echo "And add the following to crontab: "
	echo " 43 6 * * * certbot renew --post-hook 'systemctl reload nginx'"
else
	echo "$certbot_creds not found; skipping SSL cert generation."
fi
