#! /bin/bash

docker events | while read event; do
	event_type=$(echo $event | awk '{print $3}')
	echo $event_type | grep '\(kill\|stop\|start\|die\)' > /dev/null
	[[ $? != "0" ]] && continue
	echo $event_type
	id=$(echo $event | awk '{print $4}')
  inspect=$(docker inspect --format '{{ .Config.Hostname }} {{ .NetworkSettings.Ports }}' $id)
	subdomain=$(echo $inspect | awk '{print $1}')
	port=$(echo $inspect | awk '{print $3}' | sed 's/[^0-9]//g')
	if [[ $event_type == "start" ]]; then
		$(realpath $0)/../subdomx-add $subdomain $port
	else
		rm $config_path
	fi

	systemctl reload nginx
done
